// This file was generated by py/makeversionhdr.py
<<<<<<< HEAD
#define MICROPY_GIT_TAG "v1.24.0"
#define MICROPY_GIT_HASH "f212bbe83"
=======
#define MICROPY_GIT_TAG "v1.25.0"
#define MICROPY_GIT_HASH "<no hash>"
>>>>>>> 4f6d161cc529d9c7a4b43413520c4036a228fe2d
#define MICROPY_BUILD_DATE "2026-03-08"
