#pragma once

static const char ONBOARD_HTML[] =
"<!DOCTYPE html><html><head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>MimiClaw Setup</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:-apple-system,sans-serif;background:#f5f5f5;color:#333;padding:16px;max-width:480px;margin:0 auto}"
"h1{text-align:center;margin:16px 0;font-size:1.4em;color:#1a73e8}"
".card{background:#fff;border-radius:12px;margin:12px 0;box-shadow:0 1px 3px rgba(0,0,0,.12);overflow:hidden}"
".card-hdr{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;cursor:pointer;user-select:none;font-weight:600;font-size:.95em}"
".card-hdr::after{content:'\\25BC';font-size:.7em;transition:transform .2s}"
".card.collapsed .card-hdr::after{transform:rotate(-90deg)}"
".card.collapsed .card-body{display:none}"
".card-body{padding:0 16px 16px}"
"label{display:block;margin:10px 0 4px;font-size:.85em;color:#555}"
"input,select{width:100%;padding:10px 12px;border:1px solid #ddd;border-radius:8px;font-size:.95em;outline:none}"
"input:focus,select:focus{border-color:#1a73e8}"
".btn{display:block;width:100%;padding:12px;border:none;border-radius:8px;font-size:1em;font-weight:600;cursor:pointer;margin:8px 0}"
".btn-scan{background:#e8f0fe;color:#1a73e8}"
".btn-save{background:#1a73e8;color:#fff;margin-top:20px;font-size:1.1em}"
".btn:active{opacity:.8}"
".ap-list{max-height:200px;overflow-y:auto;border:1px solid #ddd;border-radius:8px;margin:8px 0}"
".ap-item{padding:10px 12px;border-bottom:1px solid #eee;cursor:pointer;display:flex;justify-content:space-between}"
".ap-item:last-child{border-bottom:none}"
".ap-item:active{background:#e8f0fe}"
".ap-rssi{color:#888;font-size:.85em}"
".ap-lock::before{content:'\\1F512';font-size:.75em;margin-right:4px}"
".status{text-align:center;padding:20px;color:#1a73e8;font-size:1.1em;display:none}"
".hint{font-size:.8em;color:#777;line-height:1.4;margin:6px 0 10px}"
"</style></head><body>"
"<h1>MimiClaw Setup</h1>"
"<p style='text-align:center;color:#666;font-size:.9em;margin-bottom:12px'>"
"This local portal remains available at 192.168.4.1 for later updates."
"</p>"

/* WiFi section (expanded by default) */
"<div class='card' id='sec-wifi'>"
"<div class='card-hdr' onclick='toggle(this)'>WiFi Configuration</div>"
"<div class='card-body'>"
"<button class='btn btn-scan' onclick='scan()'>Scan WiFi Networks</button>"
"<div class='ap-list' id='ap-list' style='display:none'></div>"
"<label>SSID</label>"
"<input id='ssid' placeholder='WiFi network name'>"
"<label>Password</label>"
"<input id='password' type='password' placeholder='WiFi password'>"
"</div></div>"

/* LLM section */
"<div class='card collapsed' id='sec-llm'>"
"<div class='card-hdr' onclick='toggle(this)'>LLM Configuration</div>"
"<div class='card-body'>"
"<label>API Key</label>"
"<input id='api_key' type='password' placeholder='API key'>"
"<label>Model</label>"
"<input id='model' placeholder='claude-opus-4-5 / qwen-max' value='claude-opus-4-5'>"
"<label>Provider</label>"
"<select id='provider'>"
"<option value='anthropic'>Anthropic</option>"
"<option value='openai'>OpenAI</option>"
"<option value='openrouter'>OpenRouter</option>"
"<option value='nvidia'>NVIDIA NIM</option>"
"<option value='qwen'>Qwen (DashScope)</option>"
"</select>"
"</div></div>"

/* Telegram section */
"<div class='card collapsed' id='sec-tg'>"
"<div class='card-hdr' onclick='toggle(this)'>Telegram Bot</div>"
"<div class='card-body'>"
"<label>Bot Token</label>"
"<input id='tg_token' placeholder='123456:ABC-DEF...'>"
"</div></div>"

/* Feishu section */
"<div class='card collapsed' id='sec-feishu'>"
"<div class='card-hdr' onclick='toggle(this)'>Feishu</div>"
"<div class='card-body'>"
"<label>App ID</label>"
"<input id='feishu_app_id' placeholder='cli_xxxx'>"
"<label>App Secret</label>"
"<input id='feishu_app_secret' type='password' placeholder='App Secret'>"
"</div></div>"

/* Proxy section */
"<div class='card collapsed' id='sec-proxy'>"
"<div class='card-hdr' onclick='toggle(this)'>Proxy</div>"
"<div class='card-body'>"
"<label>Host</label>"
"<input id='proxy_host' placeholder='192.168.1.100'>"
"<label>Port</label>"
"<input id='proxy_port' type='number' placeholder='7890'>"
"<label>Type</label>"
"<select id='proxy_type'>"
"<option value=''>None</option>"
"<option value='http'>HTTP</option>"
"<option value='socks5'>SOCKS5</option>"
"</select>"
"</div></div>"

/* Search section */
"<div class='card collapsed' id='sec-search'>"
"<div class='card-hdr' onclick='toggle(this)'>Search</div>"
"<div class='card-body'>"
"<label>Brave Search API Key</label>"
"<input id='search_key' type='password' placeholder='BSA...'>"
"<label>Tavily API Key</label>"
"<input id='tavily_key' type='password' placeholder='tvly-...'>"
"</div></div>"

/* BLE Configuration section */
"<div class='card collapsed' id='sec-ble'>"
"<div class='card-hdr' onclick='toggle(this)'>BLE Configuration</div>"
"<div class='card-body'>"
"<label>BLE Target Address</label>"
"<input id='ble_target_addr' placeholder='a4:c1:38:a0:0d:98'>"
"</div></div>"

/* Camera Configuration section */
"<div class='card collapsed' id='sec-camera'>"
"<div class='card-hdr' onclick='toggle(this)'>Camera Configuration</div>"
"<div class='card-body'>"
"<label>Camera Pin Preset</label>"
"<select id='camera_preset' onchange='applyCameraPreset(this.value)'>"
"<option value='BOARD_WROVER_KIT'>WROVER-KIT</option>"
"<option value='BOARD_ESP32CAM_AITHINKER'>ESP32-CAM AiThinker</option>"
"<option value='BOARD_ESP32S3_WROOM'>ESP32-S3 WROOM</option>"
"<option value='BOARD_ESP32S3_GOOUUU'>ESP32-S3 GOOUUU</option>"
"<option value='BOARD_ESP32S3_XIAO'>ESP32-S3 XIAO</option>"
"<option value='custom'>Custom</option>"
"</select>"
"<div class='hint'>Choose a common board preset to fill the camera pins automatically. Switch back to Custom to edit manually.</div>"
"<label>Frame Size</label>"
"<select id='camera_frame_size'>"
"<option value='0'>QQVGA (160x120)</option>"
"<option value='1'>QCIF (176x144)</option>"
"<option value='2'>HQVGA (240x176)</option>"
"<option value='4'>QVGA (320x240)</option>"
"<option value='5'>CIF (400x296)</option>"
"<option value='6'>HVGA (480x320)</option>"
"<option value='7'>VGA (640x480)</option>"
"<option value='8'>SVGA (800x600)</option>"
"<option value='9'>XGA (1024x768)</option>"
"<option value='10'>SXGA (1280x1024)</option>"
"<option value='11'>UXGA (1600x1200)</option>"
"</select>"
"<label>JPEG Quality (1-100)</label>"
"<input id='camera_jpeg_quality' type='number' min='1' max='100' placeholder='8'>"
"<hr style='margin: 16px 0; border: none; border-top: 1px solid #eee;'>"
"<label>PWDN Pin</label>"
"<input id='cam_pin_pwdn' type='number' min='-1' max='48' step='1' placeholder='12'>"
"<label>RESET Pin</label>"
"<input id='cam_pin_reset' type='number' min='-1' max='48' step='1' placeholder='40'>"
"<label>XCLK Pin</label>"
"<input id='cam_pin_xclk' type='number' min='-1' max='48' step='1' placeholder='-1'>"
"<label>XCLK Frequency (Hz)</label>"
"<input id='cam_xclk_freq' type='number' placeholder='12000000'>"
"<label>SIOD Pin</label>"
"<input id='cam_pin_siod' type='number' min='-1' max='48' step='1' placeholder='16'>"
"<label>SIOC Pin</label>"
"<input id='cam_pin_sioc' type='number' min='-1' max='48' step='1' placeholder='15'>"
"<label>D7 Pin</label>"
"<input id='cam_pin_d7' type='number' min='-1' max='48' step='1' placeholder='21'>"
"<label>D6 Pin</label>"
"<input id='cam_pin_d6' type='number' min='-1' max='48' step='1' placeholder='10'>"
"<label>D5 Pin</label>"
"<input id='cam_pin_d5' type='number' min='-1' max='48' step='1' placeholder='47'>"
"<label>D4 Pin</label>"
"<input id='cam_pin_d4' type='number' min='-1' max='48' step='1' placeholder='9'>"
"<label>D3 Pin</label>"
"<input id='cam_pin_d3' type='number' min='-1' max='48' step='1' placeholder='38'>"
"<label>D2 Pin</label>"
"<input id='cam_pin_d2' type='number' min='-1' max='48' step='1' placeholder='18'>"
"<label>D1 Pin</label>"
"<input id='cam_pin_d1' type='number' min='-1' max='48' step='1' placeholder='39'>"
"<label>D0 Pin</label>"
"<input id='cam_pin_d0' type='number' min='-1' max='48' step='1' placeholder='17'>"
"<label>VSYNC Pin</label>"
"<input id='cam_pin_vsync' type='number' min='-1' max='48' step='1' placeholder='42'>"
"<label>HREF Pin</label>"
"<input id='cam_pin_href' type='number' min='-1' max='48' step='1' placeholder='41'>"
"<label>PCLK Pin</label>"
"<input id='cam_pin_pclk' type='number' min='-1' max='48' step='1' placeholder='11'>"
"</div></div>"

/* Features section */
"<div class='card collapsed' id='sec-features'>"
"<div class='card-hdr' onclick='toggle(this)'>Features</div>"
"<div class='card-body'>"
"<style>"
".feature-item{display:flex;align-items:flex-start;gap:12px;margin:12px 0}"
".feature-item input[type='checkbox']{width:16px;height:16px;margin-top:4px;cursor:pointer}"
".feature-item input[type='checkbox']:checked{accent-color: #1a73e8;width:16px;height:16px;margin-top:4px;cursor:pointer}"
".feature-content{flex:1}"
".feature-title{font-weight:700;line-height:1.3;margin-bottom:4px}"
".feature-desc{font-size:.85em;color:#666;line-height:1.4}"
"</style>"
"<div class='feature-item'>"
"<input id='rgb_control' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>RGB Control</div>"
"<div class='feature-desc'>Control the onboard RGB LED colors and effects</div>"
"</div>"
"</div>"
"<div class='feature-item'>"
"<input id='camera_tool' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>Camera Tool</div>"
"<div class='feature-desc'>Capture images with the device's camera module</div>"
"</div>"
"</div>"
"<div class='feature-item'>"
"<input id='ble_tool' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>BLE Tool</div>"
"<div class='feature-desc'>Listen for BLE devices and receive sensor data</div>"
"</div>"
"</div>"
"<div class='feature-item'>"
"<input id='telegram_bot' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>Telegram Bot</div>"
"<div class='feature-desc'>Enable communication through Telegram bot interface</div>"
"</div>"
"</div>"
"<div class='feature-item'>"
"<input id='feishu_bot' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>Feishu Bot</div>"
"<div class='feature-desc'>Enable communication through Feishu bot interface</div>"
"</div>"
"</div>"
"</div></div>"

"<button class='btn btn-save' onclick='save()'>Save &amp; Restart</button>"
"<div class='status' id='status'>Saving... Device will restart.</div>"

"<script>"
"function toggle(el){"
"el.parentElement.classList.toggle('collapsed')}"

"var cameraPresets={"
"BOARD_WROVER_KIT:{cam_pin_pwdn:-1,cam_pin_reset:-1,cam_pin_xclk:21,cam_pin_siod:26,cam_pin_sioc:27,cam_pin_d7:35,cam_pin_d6:34,cam_pin_d5:39,cam_pin_d4:36,cam_pin_d3:19,cam_pin_d2:18,cam_pin_d1:5,cam_pin_d0:4,cam_pin_vsync:25,cam_pin_href:23,cam_pin_pclk:22},"
"BOARD_ESP32CAM_AITHINKER:{cam_pin_pwdn:32,cam_pin_reset:-1,cam_pin_xclk:0,cam_pin_siod:26,cam_pin_sioc:27,cam_pin_d7:35,cam_pin_d6:34,cam_pin_d5:39,cam_pin_d4:36,cam_pin_d3:21,cam_pin_d2:19,cam_pin_d1:18,cam_pin_d0:5,cam_pin_vsync:25,cam_pin_href:23,cam_pin_pclk:22},"
"BOARD_ESP32S3_WROOM:{cam_pin_pwdn:38,cam_pin_reset:-1,cam_pin_xclk:15,cam_pin_siod:4,cam_pin_sioc:5,cam_pin_d7:16,cam_pin_d6:17,cam_pin_d5:18,cam_pin_d4:12,cam_pin_d3:10,cam_pin_d2:8,cam_pin_d1:9,cam_pin_d0:11,cam_pin_vsync:6,cam_pin_href:7,cam_pin_pclk:13},"
"BOARD_ESP32S3_GOOUUU:{cam_pin_pwdn:-1,cam_pin_reset:-1,cam_pin_xclk:15,cam_pin_siod:4,cam_pin_sioc:5,cam_pin_d7:16,cam_pin_d6:17,cam_pin_d5:18,cam_pin_d4:12,cam_pin_d3:10,cam_pin_d2:8,cam_pin_d1:9,cam_pin_d0:11,cam_pin_vsync:6,cam_pin_href:7,cam_pin_pclk:13},"
"BOARD_ESP32S3_XIAO:{cam_pin_pwdn:-1,cam_pin_reset:-1,cam_pin_xclk:10,cam_pin_siod:40,cam_pin_sioc:39,cam_pin_d7:48,cam_pin_d6:11,cam_pin_d5:12,cam_pin_d4:14,cam_pin_d3:16,cam_pin_d2:18,cam_pin_d1:17,cam_pin_d0:15,cam_pin_vsync:38,cam_pin_href:47,cam_pin_pclk:13}"
"};"

"var cameraPresetFields=['cam_pin_pwdn','cam_pin_reset','cam_pin_xclk','cam_pin_siod','cam_pin_sioc','cam_pin_d7','cam_pin_d6','cam_pin_d5','cam_pin_d4','cam_pin_d3','cam_pin_d2','cam_pin_d1','cam_pin_d0','cam_pin_vsync','cam_pin_href','cam_pin_pclk'];"

"function detectCameraPreset(){"
"var names=Object.keys(cameraPresets);"
"for(var n=0;n<names.length;n++){"
"var name=names[n];"
"var preset=cameraPresets[name];"
"var matched=true;"
"for(var i=0;i<cameraPresetFields.length;i++){"
"var field=cameraPresetFields[i];"
"var el=document.getElementById(field);"
"if(!el || String(el.value) !== String(preset[field])){matched=false;break;}"
"}"
"if(matched){return name}"
"}"
"return 'custom'"
"}"

"function syncCameraPresetSelect(){"
"var el=document.getElementById('camera_preset');"
"if(!el){return}"
"var selected=detectCameraPreset();"
"el.value=selected;"
"setCameraPinsEditable(selected==='custom');"
"}"

"function setCameraPinsEditable(editable){"
"cameraPresetFields.forEach(function(field){"
"var el=document.getElementById(field);"
"if(!el){return}"
"el.readOnly=!editable;"
"el.style.backgroundColor=editable?'':'#f3f4f6';"
"});"
"}"

"function applyCameraPreset(name){"
"if(name==='custom'){setCameraPinsEditable(true);return}"
"var preset=cameraPresets[name];"
"if(!preset){return}"
"Object.keys(preset).forEach(function(field){"
"var el=document.getElementById(field);"
"if(el && preset[field] !== undefined){el.value=preset[field]}"
"});"
"syncCameraPresetSelect();"
"}"

"function loadConfig(){"
"fetch('/config').then(r=>r.json()).then(cfg=>{"
"Object.keys(cfg).forEach(k=>{"
"var el=document.getElementById(k);"
"if(el && cfg[k] !== undefined && cfg[k] !== null){"
"if(el.type === 'checkbox'){"
"el.checked=cfg[k]}"
"else if(el.tagName === 'SELECT'){"
"el.value=cfg[k]}"
"else{el.value=cfg[k]}"
"}"
"});"
"syncCameraPresetSelect();"
"}).catch(()=>{})}"

"function scan(){"
"var btn=event.target;btn.textContent='Scanning...';btn.disabled=true;"
"fetch('/scan').then(r=>r.json()).then(list=>{"
"var el=document.getElementById('ap-list');el.style.display='block';el.innerHTML='';"
"list.forEach(ap=>{"
"var d=document.createElement('div');d.className='ap-item';"
"d.innerHTML='<span>'+(ap.auth?'<span class=ap-lock></span>':'')+ap.ssid+'</span><span class=ap-rssi>'+ap.rssi+' dBm</span>';"
"d.onclick=function(){document.getElementById('ssid').value=ap.ssid};"
"el.appendChild(d)});"
"btn.textContent='Scan WiFi Networks';btn.disabled=false;"
"}).catch(()=>{btn.textContent='Scan WiFi Networks';btn.disabled=false})}"

"function save(){"
"var fields=['ssid','password','api_key','model','provider','tg_token',"
"'feishu_app_id','feishu_app_secret','proxy_host','proxy_port','proxy_type','search_key','tavily_key','ble_target_addr'];"
"var boolFields=['rgb_control','camera_tool','ble_tool','telegram_bot','feishu_bot'];"
"var numberFields=['camera_frame_size','camera_jpeg_quality','cam_pin_pwdn','cam_pin_reset','cam_pin_xclk','cam_xclk_freq','cam_pin_siod','cam_pin_sioc','cam_pin_d7','cam_pin_d6','cam_pin_d5','cam_pin_d4','cam_pin_d3','cam_pin_d2','cam_pin_d1','cam_pin_d0','cam_pin_vsync','cam_pin_href','cam_pin_pclk'];"
"for(var i=0;i<cameraPresetFields.length;i++){"
"    var pinField=cameraPresetFields[i];"
"    var pinEl=document.getElementById(pinField);"
"    if(!pinEl || pinEl.readOnly){continue;}"
"    var pinValue=pinEl.value.trim();"
"    if(pinValue===''){continue;}"
"    if(!/^-?\\d+$/.test(pinValue)){"
"        document.getElementById('status').style.display='block';"
"        document.getElementById('status').textContent='Invalid '+pinField+': must be integer -1 to 48';"
"        return;"
"    }"
"    var pin=parseInt(pinValue,10);"
"    if(pin<-1 || pin>48){"
"        document.getElementById('status').style.display='block';"
"        document.getElementById('status').textContent='Invalid '+pinField+': out of range (-1 to 48)';"
"        return;"
"    }"
"}"
"var data={};"
"fields.forEach(f=>{"
"    var el=document.getElementById(f);"
"    if(el) data[f]=el.value.trim();"
"});"
"boolFields.forEach(f=>{"
"    var el=document.getElementById(f);"
"    if(el) data[f]=el.checked;"
"});"
"numberFields.forEach(f=>{"
"    var el=document.getElementById(f);"
"    if(el){"
"        var value = el.value;"
"        if(value === ''){"
"            var defaults = {"
"                'camera_frame_size': 7,"
"                'camera_jpeg_quality': 8,"
"                'cam_pin_pwdn': 12,"
"                'cam_pin_reset': 40,"
"                'cam_pin_xclk': -1,"
"                'cam_pin_siod': 16,"
"                'cam_pin_sioc': 15,"
"                'cam_pin_d7': 21,"
"                'cam_pin_d6': 10,"
"                'cam_pin_d5': 47,"
"                'cam_pin_d4': 9,"
"                'cam_pin_d3': 38,"
"                'cam_pin_d2': 18,"
"                'cam_pin_d1': 39,"
"                'cam_pin_d0': 17,"
"                'cam_pin_vsync': 42,"
"                'cam_pin_href': 41,"
"                'cam_pin_pclk': 11,"
"                'cam_xclk_freq': 12000000"
"            };"
"            data[f] = defaults[f] || 0;"
"        } else {"
"            data[f] = parseInt(value,10);"
"        }"
"    }"
"});"
"console.log('Saving configuration:', data);"
"document.getElementById('status').style.display='block';"
"fetch('/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})"
".then(()=>{document.getElementById('status').textContent='Saved! Restarting...';})"
".catch(()=>{document.getElementById('status').textContent='Error. Please try again.';})}"
"loadConfig();"
"</script>"
"</body></html>";
