#pragma once

static const char ONBOARD_HTML[] =
"<!DOCTYPE html><html><head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>MimiClaw Setup</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:-apple-system,sans-serif;background:#f5f5f5;color:#333;padding:16px;max-width:480px;margin:0 auto}"
"h1{text-align:center;margin:16px 0;font-size:1.4em;color:#1a73e8}"
".card{background:#fff;border-radius:12px;margin:12px 0;box-shadow:0 1px 3px rgba(0,0,0,.12);overflow:hidden}"
".card-hdr{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;cursor:pointer;user-select:none;font-weight:600;font-size:.95em}"
".card-hdr::after{content:'\\25BC';font-size:.7em;transition:transform .2s}"
".card.collapsed .card-hdr::after{transform:rotate(-90deg)}"
".card.collapsed .card-body{display:none}"
".card-body{padding:0 16px 16px}"
"label{display:block;margin:10px 0 4px;font-size:.85em;color:#555}"
"input,select{width:100%;padding:10px 12px;border:1px solid #ddd;border-radius:8px;font-size:.95em;outline:none}"
"textarea{width:100%;padding:10px 12px;border:1px solid #ddd;border-radius:8px;font-size:.95em;outline:none;resize:vertical;min-height:110px}"
"input:focus,select:focus,textarea:focus{border-color:#1a73e8}"
".btn{display:block;width:100%;padding:12px;border:none;border-radius:8px;font-size:1em;font-weight:600;cursor:pointer;margin:8px 0}"
".btn-scan{background:#e8f0fe;color:#1a73e8}"
".btn-save{background:#1a73e8;color:#fff;margin-top:20px;font-size:1.1em}"
".btn:active{opacity:.8}"
".ap-list{max-height:200px;overflow-y:auto;border:1px solid #ddd;border-radius:8px;margin:8px 0}"
".ap-item{padding:10px 12px;border-bottom:1px solid #eee;cursor:pointer;display:flex;justify-content:space-between}"
".ap-item:last-child{border-bottom:none}"
".ap-item:active{background:#e8f0fe}"
".ap-rssi{color:#888;font-size:.85em}"
".ap-lock::before{content:'\\1F512';font-size:.75em;margin-right:4px}"
".status{text-align:center;padding:20px;color:#1a73e8;font-size:1.1em;display:none}"
".hint{font-size:.8em;color:#777;line-height:1.4;margin:6px 0 10px}"
"</style></head><body>"
"<h1>MimiClaw Setup</h1>"
"<p style='text-align:center;color:#666;font-size:.9em;margin-bottom:12px'>"
"This local portal remains available at 192.168.4.1 for later updates."
"</p>"

/* WiFi section (expanded by default) */
"<div class='card' id='sec-wifi'>"
"<div class='card-hdr' onclick='toggle(this)'>WiFi Configuration</div>"
"<div class='card-body'>"
"<button class='btn btn-scan' onclick='scan()'>Scan WiFi Networks</button>"
"<div class='ap-list' id='ap-list' style='display:none'></div>"
"<label>SSID</label>"
"<input id='ssid' placeholder='WiFi network name'>"
"<label>Password</label>"
"<input id='password' type='password' placeholder='WiFi password'>"
"</div></div>"

/* LLM section */
"<div class='card collapsed' id='sec-llm'>"
"<div class='card-hdr' onclick='toggle(this)'>LLM Configuration</div>"
"<div class='card-body'>"
"<label>API Key</label>"
"<input id='api_key' type='password' placeholder='API key'>"
"<label>Model</label>"
"<input id='model' placeholder='claude-opus-4-5 / qwen-max' value='claude-opus-4-5'>"
"<label>Provider</label>"
"<select id='provider'>"
"<option value='anthropic'>Anthropic</option>"
"<option value='openai'>OpenAI</option>"
"<option value='openrouter'>OpenRouter</option>"
"<option value='nvidia'>NVIDIA NIM</option>"
"<option value='qwen'>Qwen (DashScope)</option>"
"</select>"
"<label>Identity System Prompt</label>"
"<textarea id='system_prompt' placeholder='Optional identity block shown at the top of system prompt'></textarea>"
"</div></div>"

/* Telegram section */
"<div class='card collapsed' id='sec-tg'>"
"<div class='card-hdr' onclick='toggle(this)'>Telegram Bot</div>"
"<div class='card-body'>"
"<label>Bot Token</label>"
"<input id='tg_token' placeholder='123456:ABC-DEF...'>"
"</div></div>"

/* Feishu section */
"<div class='card collapsed' id='sec-feishu'>"
"<div class='card-hdr' onclick='toggle(this)'>Feishu</div>"
"<div class='card-body'>"
"<label>App ID</label>"
"<input id='feishu_app_id' placeholder='cli_xxxx'>"
"<label>App Secret</label>"
"<input id='feishu_app_secret' type='password' placeholder='App Secret'>"
"</div></div>"

/* Proxy section */
"<div class='card collapsed' id='sec-proxy'>"
"<div class='card-hdr' onclick='toggle(this)'>Proxy</div>"
"<div class='card-body'>"
"<label>Host</label>"
"<input id='proxy_host' placeholder='192.168.1.100'>"
"<label>Port</label>"
"<input id='proxy_port' type='number' placeholder='7890'>"
"<label>Type</label>"
"<select id='proxy_type'>"
"<option value=''>None</option>"
"<option value='http'>HTTP</option>"
"<option value='socks5'>SOCKS5</option>"
"</select>"
"</div></div>"

/* Search section */
"<div class='card collapsed' id='sec-search'>"
"<div class='card-hdr' onclick='toggle(this)'>Search</div>"
"<div class='card-body'>"
"<label>Brave Search API Key</label>"
"<input id='search_key' type='password' placeholder='BSA...'>"
"<label>Tavily API Key</label>"
"<input id='tavily_key' type='password' placeholder='tvly-...'>"
"</div></div>"

/* Device capability configuration note */
"<div class='card collapsed' id='sec-device-capability'>"
"<div class='card-hdr' onclick='toggle(this)'>Device Capability Configuration</div>"
"<div class='card-body'>"
"<div class='hint'>Camera and BLE detailed configuration has moved out of onboarding. Please let the agent configure camera_core and bthome_listener via Lua libraries.</div>"
"</div></div>"

/* Features section */
"<div class='card collapsed' id='sec-features'>"
"<div class='card-hdr' onclick='toggle(this)'>Features</div>"
"<div class='card-body'>"
"<style>"
".feature-item{display:flex;align-items:flex-start;gap:12px;margin:12px 0}"
".feature-item input[type='checkbox']{width:16px;height:16px;margin-top:4px;cursor:pointer}"
".feature-item input[type='checkbox']:checked{accent-color: #1a73e8;width:16px;height:16px;margin-top:4px;cursor:pointer}"
".feature-content{flex:1}"
".feature-title{font-weight:700;line-height:1.3;margin-bottom:4px}"
".feature-desc{font-size:.85em;color:#666;line-height:1.4}"
"</style>"
"<div class='feature-item' id='feature_rgb_control'>"
"<input id='rgb_control' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>RGB Control</div>"
"<div class='feature-desc'>Control the onboard RGB LED colors and effects</div>"
"</div>"
"</div>"
"<div class='feature-item' id='feature_camera_tool'>"
"<input id='camera_tool' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>Camera Tool</div>"
"<div class='feature-desc'>Capture images with the device's camera module</div>"
"</div>"
"</div>"
"<div class='feature-item' id='feature_camera_server'>"
"<input id='camera_server' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>Camera Server</div>"
"<div class='feature-desc'>Enable HTTP camera endpoint at /capture for external access</div>"
"</div>"
"</div>"
"<div class='feature-item' id='feature_ble_tool'>"
"<input id='ble_tool' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>BLE Tool</div>"
"<div class='feature-desc'>Listen for BLE devices and receive sensor data</div>"
"</div>"
"</div>"
"<div class='feature-item'>"
"<input id='telegram_bot' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>Telegram Bot</div>"
"<div class='feature-desc'>Enable communication through Telegram bot interface</div>"
"</div>"
"</div>"
"<div class='feature-item'>"
"<input id='feishu_bot' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>Feishu Bot</div>"
"<div class='feature-desc'>Enable communication through Feishu bot interface</div>"
"</div>"
"</div>"
"</div></div>"

"<button class='btn btn-save' onclick='save()'>Save &amp; Restart</button>"
"<div class='status' id='status'>Saving... Device will restart.</div>"

"<script>"
"function toggle(el){"
"el.parentElement.classList.toggle('collapsed')}"


"function loadConfig(){"
"fetch('/config').then(r=>r.json()).then(cfg=>{"
"Object.keys(cfg).forEach(k=>{"
"var el=document.getElementById(k);"
"if(el && cfg[k] !== undefined && cfg[k] !== null){"
"if(el.type === 'checkbox'){"
"el.checked=cfg[k]}"
"else if(el.tagName === 'SELECT'){"
"el.value=cfg[k]}"
"else{el.value=cfg[k]}"
"}"
"});"
"applyBuildAvailability(cfg);"
"}).catch(()=>{})}"

"function scan(){"
"var btn=event.target;btn.textContent='Scanning...';btn.disabled=true;"
"fetch('/scan').then(r=>r.json()).then(list=>{"
"var el=document.getElementById('ap-list');el.style.display='block';el.innerHTML='';"
"list.forEach(ap=>{"
"var d=document.createElement('div');d.className='ap-item';"
"d.innerHTML='<span>'+(ap.auth?'<span class=ap-lock></span>':'')+ap.ssid+'</span><span class=ap-rssi>'+ap.rssi+' dBm</span>';"
"d.onclick=function(){document.getElementById('ssid').value=ap.ssid};"
"el.appendChild(d)});"
"btn.textContent='Scan WiFi Networks';btn.disabled=false;"
"}).catch(()=>{btn.textContent='Scan WiFi Networks';btn.disabled=false})}"

"function save(){"
"var fields=['ssid','password','api_key','model','provider','system_prompt','tg_token',"
"'feishu_app_id','feishu_app_secret','proxy_host','proxy_port','proxy_type','search_key','tavily_key'];"
"var boolFields=['rgb_control','camera_tool','camera_server','ble_tool','telegram_bot','feishu_bot'];"
"var data={};"
"fields.forEach(f=>{"
"    var el=document.getElementById(f);"
"    if(el) data[f]=el.value.trim();"
"});"
"boolFields.forEach(f=>{"
"    var el=document.getElementById(f);"
"    if(el) data[f]=el.checked;"
"});"
"console.log('Saving configuration:', data);"
"document.getElementById('status').style.display='block';"
"fetch('/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})"
".then(()=>{document.getElementById('status').textContent='Saved! Restarting...';})"
".catch(()=>{document.getElementById('status').textContent='Error. Please try again.';})}"
"function setFeatureAvailability(id, available){"
"var row=document.getElementById('feature_'+id);"
"var cb=document.getElementById(id);"
"if(!row || !cb){return}"
"if(available){"
"row.style.display='flex';"
"cb.disabled=false;"
"return;"
"}"
"row.style.display='none';"
"cb.checked=false;"
"cb.disabled=true;"
"}"
"function setSectionVisible(id, visible){"
"var el=document.getElementById(id);"
"if(el){"
"el.style.display = visible ? '' : 'none';"
"}"
"}"
"var featureAvailability = {rgb_control:true, camera_tool:true, camera_server:true, ble_tool:true};"
"function updateDependentVisibility(){"
"var cameraToolEl=document.getElementById('camera_tool');"
"var cameraToolEnabled=!!(cameraToolEl && cameraToolEl.checked);"
"setFeatureAvailability('camera_server', cameraToolEnabled && featureAvailability.camera_server !== false);"
"}"
"function applyBuildAvailability(cfg){"
"featureAvailability.rgb_control = cfg.rgb_control_available !== false;"
"featureAvailability.camera_tool = cfg.camera_tool_available !== false;"
"featureAvailability.camera_server = cfg.camera_server_available !== false;"
"featureAvailability.ble_tool = cfg.ble_tool_available !== false;"
"setFeatureAvailability('rgb_control', cfg.rgb_control_available !== false);"
"setFeatureAvailability('camera_tool', cfg.camera_tool_available !== false);"
"setFeatureAvailability('camera_server', cfg.camera_server_available !== false);"
"setFeatureAvailability('ble_tool', cfg.ble_tool_available !== false);"
"updateDependentVisibility();"
"}"

"document.addEventListener('DOMContentLoaded', function(){"
"var cameraToolEl = document.getElementById('camera_tool');"
"if(cameraToolEl){"
"cameraToolEl.addEventListener('change', updateDependentVisibility);"
"}"
"var bleToolEl = document.getElementById('ble_tool');"
"if(bleToolEl){"
"bleToolEl.addEventListener('change', updateDependentVisibility);"
"}"
"});"

"loadConfig();"
"</script>"
"</body></html>";
